# Load theme
source-file "${HOME}/.tmux/tmux-gruvbox-dark.conf"

# Make zsh default
set -g default-command /usr/bin/zsh

# Make vim keys work as expected
set-window-option -g xterm-keys on
set -g default-terminal "xterm-256color"
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Enable mouse
set -g mouse on

# Enable fast commands
set -s escape-time 0

# Enable vi mode
set-window-option -g mode-keys vi
# Copy to clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'

# Start indexing from 1
set -g base-index 1        # starts window numbering from 1
set -g pane-base-index 1   # starts pane numbering from 1

# Window settings
set-option -g status-interval 1

# Open new windows, split-windows with current path
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    set window-status-current-format "#[fg=$color_window_off_status_bg,bg=$color_window_off_status_current_bg]$separator_powerline_right#[default] #I:#W# #[fg=$color_window_off_status_current_bg,bg=$color_window_off_status_bg]$separator_powerline_right#[default]" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u window-status-current-format \;\
  refresh-client -S
